### PR TITLE
Remove previous WP-to-GH config file

### PR DESCRIPTION
**Pull request by xjensen**
Following #220 and cagov/services-wordpress-to-github-drought-ca-gov#2, this PR removes previous `wordpress-to-github.config.json` configuration files. These files now live in the `odi-publishing` folder.

### CODE REVIEW

**Review by aaronhans — APPROVED** [review]
cool

**Review by carterm — APPROVED** [review]
Removing general file and wpgh config.

**Comment by carterm** [comment]
Note that there is a ref to the staging branch still here...
https://github.com/cagov/services-wordpress-to-github-drought-ca-gov/blob/main/WordpressSync/endpoints.json

**Comment by xjensen** [comment]
Yep, I will need to sync up `staging` and other branches in follow-up PRs.

**Pull request merged**
