### PR TITLE
Update staging

### PR DESCRIPTION
**Pull request by xjensen**
Brings `staging` up-to-date with recent changes in `main`. 

There were a lot of old, prospective-looking projects in `staging` that never made the jump to `main`. I tried to respect as much of this as possible. 

This will require a change to the staging wordpress-to-github endpoint configuration. I'll go do that shortly.

### CODE REVIEW

**Comment by carterm** [comment]
That's a huge change.  Almost better to just re-base staging for this much?

**Comment by xjensen** [comment]
There are a lot of side-projects in `staging` that never made the jump to `main`. Rebase makes sense if we're okay with removing all of those extra things. 

I prefer this approach, to be honest. I think `staging` should match `main` for purposes of content preview. But I don't want to accidentally delete something important.

**Review by kkoryaka — APPROVED** [review]
let's bring it up to date

**Comment by xjensen** [comment]
There was a hard-to-debug problem in the build here. Ultimately this was due to a problem in `package-lock.json`, the `devDependencies` in this branch related to Cypress, and conflicts with using `npm ci --production` in the GitHub environment. Since we're planning to standardize on Playwright anyway, removing Cypress seems like a good response.

**Pull request merged**
