### PR TITLE
Reorganize templates

### PR DESCRIPTION
**Pull request by xjensen**
This PR aims to simplify how we process content data. It's a draft.

Currently, we push HTML and JSON for each page (to the repo) from Wordpress. **We then run a lot of code to read, associate, and process those content files.** Much of this reading, associating, and processing could be handled by 11ty's built-in capabilities instead. In particular, this PR makes greater use of the [11ty Data Cascade](https://www.11ty.dev/docs/data-cascade/) and [11ty Layouts](https://www.11ty.dev/docs/layouts/).

> "Let 11ty do the work." --@xjensen

It's a big PR. Here's a summary of the changes.

## The `wordpress` folder split-up

I had to move the content folders to new locations to include them within the 11ty Data Cascade. Here's where the files live now.

The `wordpress/pages` and `wordpress/posts` folders have been moved to `src/templates/wordpress`. By moving these two content folders into 11ty's input folder (which is `src/templates` for this repo), 11ty will automatically link up HTML files with JSON files of the same name, then insert that JSON data into the HTML's templating. This doesn't require any code or configuration. 11ty does this by default.

The `wordpress/media` folder has been moved to `src/wordpress-media`. Since we don't really need 11ty to process these media files, I moved them outside of the 11ty input folder. This cleans up the 11ty pipeline and allows for a simple `addPassthroughCopy` directive.

The `wordpress/general/general.json` and `wordpress/wordpress-to-github.json` files have been moved to `odi-publishing`. With the rest of the former `wordpress` folder broken up, the `odi-publishing` folder felt like a better home for these files. This would, of course, require a change to the endpoints within wordpress-to-github service.

## The `wordpress.11tydata.js` file

There's a new file at `src/templates/wordpress/wordpress.11tydata.js`. The name and location of this file are both important. This file tells 11ty, "Apply the data in this file to all templates within this folder." **We can therefore easily set defaults for Wordpress content data within this file.**

An important note here is the `eleventyComputed` key in the output of this file. This key triggers the [11ty Computed Data](https://www.11ty.dev/docs/data-computed/) feature. In summary, this allows us to process each individual article's data. 

> We could further simplify this file with a change to the Wordpress API (or wordpress-to-github). The Wordpress API currently outputs blank string values for missing data, rather than simply omitting a blank property altogether. Because the 11ty Data Cascade uses the most local declaration of data, it will choose those blank strings (within an article's JSON) instead of using defaults in `wordpress.11tydata.js`. Therefore, we need to use `eleventyComputed` to evaluate the article's data before applying defaults. If we could omit missing data keys from the Wordpress content JSON files, we could remove many of the `eleventyComputed` functions in favor of very simple key:value default definitions. If that makes any sense.

## Layouts

By rearranging includes and layout files, we can rely on 11ty's layout engine instead of manually processing template strings. 

## Removals

The above changes allow us to remove the `src/templates/_data/meta.js` and `src/templates/_data/wordpress.js` files. We can also remove all of the manual collection processing within the `.eleventy.js` file.

## Results

This approach overall removes a significant volume of code and complexity. In my testing so far, it also cuts the 11ty build time in half.

## Still to-do

We need a more robust way to set the site's domain based on environment: localhost, drought.ca.gov, staging.drought.ca.gov, etc. I plan to achieve this through a combination of environment variable and GitHub Action.

## Final notes

This may be a controversial PR because it challenges assumptions about how we write, store, and process Wordpress data within an 11ty repo. All discussion is welcome. The goal here is to make best use of 11ty to simplify how we configure and maintain our static sites.

### CODE REVIEW

**Comment by zakiya** [comment]
I don't have any investment in the current way we write templates so this all looks like it's moving in the right direction to me. Two notes:

- I'd like to see these changes eventually rolled up into odi-publishing. I think we should decide what repo should be the destination for the starter kit. 
- This is a situation where visual regression testing would be super useful.

**Comment by aaronhans** [comment]
This is great, I like the simplification of logic in .eleventy.js and the application of it directly to folders where it is relevant.

We'll need to document this everywhere it is used because new devs need to know where to find this logic

I like @zakiya 's point about centralizing this approach. I think this is a great step in that direction because wordpress specific logic is moving out of universal files

**Comment by xjensen** [comment]
Fully agreed on all points. I'll roll this into the sandbox when it's ready. (I need to bring the other branches into parity with `main` too.)

This is ready.

**Review by aaronhans — APPROVED** [review]
Nice simplification of logic in 11ty, lot of file renames, thanks for adding section to readme describing where new configuration is happening

**Comment by chachasikes** [comment]
“The wordpress/general/general.json and wordpress/wordpress-to-github.json files have been moved to odi-publishing. With the rest of the former wordpress folder broken up, the odi-publishing folder felt like a better home for these files. This would, of course, require a change to the endpoints within wordpress-to-github service.”

So happy to see this.

This touches on the danger zone code. I think wordpress-to-github has been sufficiently updates to make sure to not delete the entire folder, but general.json had some destructive actions, so giving a heads up.

**Comment by chachasikes** [comment]
"We need a more robust way to set the site's domain based on environment: localhost, drought.ca.gov, staging.drought.ca.gov, etc. I plan to achieve this through a combination of environment variable and GitHub Action."

Fully approve.

Notes: 
* We will need to train team on env vars & also on key sharing with our shared security tool & cross-train on updating the keys in Github.
* I can't think of any implications in WordPress yet (regarding Github actions & builds) - but there will be a companion UI in wordpress plugin for connecting to these services & we will need to work out how we communicate about this. (And then how we train other teams to communicate about this/maintain it)

**Pull request merged**
