### PR TITLE
Update to newer Design System components

### PR DESCRIPTION
**Pull request by xjensen**
To verify changes in cagov/design-system#190, we needed to update all the Design System components on Drought. Here's the PR. Now that all those Design System components are live, we can think about pushing this live too. Many of these changes have already been in staging for some time. 

But wait, there's more!

Per #204, while updating the components, I also cleaned out a lot of old, redundant code. This old code is replaced by equivalent code from the Design System. That's why the diff on this PR will likely be very large.

### CODE REVIEW

**Comment by xjensen** [comment]
Marking as draft while I test on different browsers/platforms.

**Review by aaronhans — COMMENTED** [review]
nice cleanup

**Comment by xjensen** [comment]
Tested on Chrome, Firefox, Edge, and Safari. Looks good throughout, with a few exceptions that pre-date the  mega-PR at cagov/design-system#190.

* ds-feature-card nukes the margins on h3 elements across all of Drought. 
* Finally found the culprit for an elusive bug that sometimes made ds-external-link-icon's icons enormous. 

I'll fix both of these issues in the Design System repo. But we have temporary overrides in Drought for now.

**Comment by xjensen** [comment]
Putting this back into draft. We should publish the mega-PR components to npm before merging this into Drought.

**Review by aaronhans — APPROVED** [review]
new components

very nice cleanup of local versions of components and unused sass files!

**Pull request merged**
